language: php

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source

php:
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4"

script:
  - phpunit --configuration ./config/travis-ci.xml

matrix:
  allow_failures:
    - php:
      - "7.1"
      - "7.4"

notifications:
  email:
    recipients:
      - nbraczek@bsds.de
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # default: false

