@startuml
class SqlControllerSql {
    #command : string
    #fields : array
    #file : string
    #id : int
    #key : string
    #limit : int
    #model : SqlModelSql
    #query : string
    #table : string
    +add() : void
    +apply() : void
    +cancel() : void
    +csv() : void
    +delete() : void
    +display() : JControllerLegacy
    +edit() : void
    +save() : void
    +saveQuery() : void
    +setParameters() : void
    +__construct(factory : Celtic.Abstraction.VersionFactoryInterface, config : array = [])
}
class SqlControllerSql extends SqlController
@enduml
